In [24]:
import torch
from transformers import *
import numpy as np

In [25]:
pretrained_weights = 'xlnet-base-cased'

In [26]:
model = XLNetModel.from_pretrained(pretrained_weights,
                                        output_hidden_states=True,
                                        output_attentions=True)

In [27]:
# model = BertForNextSentencePrediction.from_pretrained(pretrained_weights,
#                                         output_hidden_states=True,
#                                         output_attentions=True)

In [28]:
tokenizer = XLNetTokenizer.from_pretrained(pretrained_weights)

In [29]:
text = "Let's see all hidden-states and attentions on this text"

In [30]:
tokenized_text = tokenizer.tokenize(text)

indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)

for tup in zip(tokenized_text, indexed_tokens):
    print('{:<11} {}'.format(tup[0], tup[1]))

▁Let        2834
'           26
s           23
▁see        197
▁all        71
▁hidden     4869
-           13
state       3566
s           23
▁and        21
▁attention  1219
s           23
▁on         31
▁this       52
▁text       1758


In [6]:
input_ids = torch.tensor([tokenizer.encode("Let's see all hidden-states and attentions on this text")])

In [7]:
input_ids

tensor([[2834,   26,   23,  197,   71, 4869,   13, 3566,   23,   21, 1219,   23,
           31,   52, 1758]])

In [8]:
all_hidden_states, all_attentions = model(input_ids)[-2:]

In [9]:
len(all_attentions)

12

In [11]:
for i in all_attentions:
    print(i.shape)

torch.Size([1, 12, 15, 15])
torch.Size([1, 12, 15, 15])
torch.Size([1, 12, 15, 15])
torch.Size([1, 12, 15, 15])
torch.Size([1, 12, 15, 15])
torch.Size([1, 12, 15, 15])
torch.Size([1, 12, 15, 15])
torch.Size([1, 12, 15, 15])
torch.Size([1, 12, 15, 15])
torch.Size([1, 12, 15, 15])
torch.Size([1, 12, 15, 15])
torch.Size([1, 12, 15, 15])


In [19]:
a = all_attentions[11].cpu().detach().numpy()

In [20]:
a.shape

(1, 12, 15, 15)

In [21]:
a.sum(1)[0].shape

(15, 15)

In [22]:
np.argmax(a.sum(1)[0], axis=0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.argmax(a.sum(1)[0], axis=1)

array([ 0,  1,  1,  3,  4,  5,  5,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
sentence_0 = "This research was consistent with his findings."
sentence_1 = "His findings were compatible with this research."
sentence_2 = "His findings were not compatible with this research."
inputs_1 = tokenizer.encode_plus(sentence_0, sentence_1, add_special_tokens=True, return_tensors='pt')
inputs_2 = tokenizer.encode_plus(sentence_0, sentence_2, add_special_tokens=True, return_tensors='pt')

In [ ]:
pred_1 = model(inputs_1['input_ids'], token_type_ids=inputs_1['token_type_ids'])[0].argmax().item()
pred_2 = model(inputs_2['input_ids'], token_type_ids=inputs_2['token_type_ids'])[0].argmax().item()

In [ ]:
pred_2

In [ ]:
print("sentence_1 is", "a paraphrase" if pred_1 else "not a paraphrase", "of sentence_0")
print("sentence_2 is", "a paraphrase" if pred_2 else "not a paraphrase", "of sentence_0")